Show done apps
kitaindia/lagoon-mgr pull request #22
Opened 2016-09-24 23:28 UTC by kitaindia

2016-09-27 22:33 UTC, kitaindia commented
@kayhide

2016-09-28 00:50 UTC, kayhide requested changes
レビューしました。
ご確認ください。

2016-09-28 00:50 UTC, kayhide commented on app/controllers/applists_controller.rb
> +    if user_applist.update_attributes(is_done: true, review_done_datetime: Time.zone.now)
`update_attributes` は `update` で置き換えられます。
https://github.com/rails/rails/blob/a8ee3a0ddce7b4af5e4fb058da250b439d0eaa3e/activerecord/lib/active_record/persistence.rb#L271

2016-09-28 00:50 UTC, kayhide commented on app/controllers/applists_controller.rb
> +EOL
`EOL` は、一般的には行末 (end of line) という意味で使われるので、ここは違うものにしたいですね。
`EOS` (end of string) なんかがおすすめです。

2016-09-28 00:50 UTC, kayhide commented on app/controllers/home_controller.rb
> +      current_user.user_applists.is_done.includes(applist: [:itunes_app, :google_play_app]).order('review_done_datetime DESC')
横長なので適当に改行をいれるとよいです。
こんな感じがよいでしょうかね。

``` ruby
    @done_reviewing_apps =
      current_user.user_applists.is_done
      .includes(applist: [:itunes_app, :google_play_app])
      .order('review_done_datetime DESC')
```

2016-09-28 00:50 UTC, kayhide commented on app/controllers/home_controller.rb
> +      current_user.user_applists.is_done.includes(applist: [:itunes_app, :google_play_app]).order('review_done_datetime DESC')
`order` ではこんな書き方もできます。

``` ruby
.order(review_done_datetime: :desc)
```

2016-09-28 00:50 UTC, kayhide commented on app/models/applist.rb
> +  def scrape_app
このメソッドの挙動は、このようになっていますね。

- `itunes_result` か `google_play_result` のいずれかが `nil` なら `false`
- それ以外なら
  - `itunes_result` か `google_play_result` のいずれかが `true` 的なら、 `true`
  - それ以外なら `false`

`scrape_app` を使っているところでは `true` ならスクレイピングが成功したと判断しているようです。
`self.update_attributes(is_scraped: true)` が失敗しても `true` を返すのは、問題がありそうですね。

2016-09-28 00:50 UTC, kayhide commented on app/models/applist.rb
> +  def scrape_app
このメソッドは場合分けが多いので、テストを書いた方がよさそうですね。
テストで全ての場合分けを網羅して、それらが意図どおりになるか、を確認してくださいませ。

generator に `rspec:model` というのがありますので、それを使うとよいでしょう。

2016-09-28 00:50 UTC, kayhide commented on app/models/applist.rb
>    def fetch_itunes_app
返り値で `nil` と `false` が区別されるのはややこしいですね。
呼び出し元の `scrape_app` でもコメントが書かれているくらいですので、設計を見直したいところです。

一案ですが、このようにしてはいかがでしょう？
- `itunes_app_params` というメソッドを作る。
- その中で `contry_code` と `app_id` の抽出や変換を試みて、`Hash` にして返す。
- 何らかの不備があれば `nil` を返す。

こうしておけば、このように書き換えることができます。
```rb
  def fetch_itunes_app
    params = itunes_app_params
    return unless params

    response = open("https://itunes.apple.com/#{params[:country_code]}/lookup?id=#{params[:app_id]}")
    code, message = response.status
    if code == '200'
      json = ActiveSupport::JSON.decode(response.read)
      result = json['results'][0]
      ItunesApp.new(
        icon_url: result['artworkUrl100'],
        name: result['trackName'],
        applist_id: self.id
      )
    end
  end
```

2016-09-28 00:50 UTC, kayhide commented on app/models/applist.rb
> +  def scrape_app
`fetch_itunes_app` の動作とも関連しますので、そちらとあわせて見直してください。
`fetch_google_play` の方も同様です。

2016-09-30 06:21 UTC, kitaindia commented on app/models/applist.rb
> +  def scrape_app
ここのnilとfalseの部分をわけている箇所、ちょっと悩んで実装しました。

nilとfalseで分けている理由は、
１．URLとしてただしくてもURL先のアプリが公開終了してたときはnilで返す。google_playとitunesのurl両方指定していて片方が成功してももう片方がfetchに失敗したら保存したくないのでそのときは失敗としてfalseにして保存を行わない
２．ただし、google_playのアプリだけしか無い場合はgoogle_playのURLだけ指定してitunesのURLを指定しない(ブランクの状態　itunes_result =falseになる)ので、そのときはgoogle_playのほうだけ保存してtrueを返す。

fetch_itunes_appをnilだけを返すようにするとすると、scrape_appのメソッドでは
itunes_url.present? と言った感じで「文字列が入っているか」みたいなのをチェックする感じにすればよいのでしょうか

2016-09-30 12:53 UTC, kayhide commented on app/models/applist.rb
> +  def scrape_app
基本的な考え方としては、期待通りに動作したら `true` 的、そうでなければ `false` 的、を前提にするのがよいです。
それを踏まえて、「何が期待どおりの動作なのか」を定める必要がありますね。

`fetch_itunes_app` で期待どおりの動作として、考え方は2つあると思います。

- itunes_url が空なら何もせずに成功、itunes_url があった場合、取得できたら成功。
- itunes_url があってもなくても、取得できなかったら失敗。

まずは、これをどちらにするか決めてください。
これが決まれば、`scrape_app` メソッドをどうすればよいかわかりやすくなるはずです。

2016-09-30 12:55 UTC, kayhide commented on app/models/applist.rb
> +  def scrape_app
そして、仕様（＝期待通りの動作）を決めたら、テストを書いてみてください。
テストを書くことによって、メソッドの役割が整理できます。

2016-10-01 03:31 UTC, kitaindia commented on app/models/applist.rb
> +  def scrape_app
>itunes_url があってもなくても、取得できなかったら失敗。

こちらのがしっくり来ました。ちょっとやってみます！

2016-10-02 05:00 UTC, kitaindia commented
以下対応しました。

・google_play_params、itunes_app_paramsというようにメソッドを分けた
・scrape_appの設計を見直し。itune_appとgoogle_play_appのsave, self.update(is_scraped: true)をトランザクションの中でおこない、 データの取得に失敗、URL先が404だった場合の例外が起きた際の対応を行った。 save!もfetch_itunes_appがnil(データが取得できない)の場合はNoMethod Errorになるし、データが重複していた場合には例外エラーが起きるようになってるので安全です。
・scrape_appのmodelのテストを書いた。テストデータを作る際前のデータが入っているとエラーが起きるのでdatabase_cleanerを導入してテスト実行のたびにdbをリセットするようにした。

2016-10-02 13:38 UTC, kayhide requested changes
FactoryGirl の書き方にコメントしました。
ご確認くださいませ。

2016-10-02 13:38 UTC, kayhide commented on spec/factories/applists.rb
> +  end
`FactoryGirl` の方針としては、デフォルトで `valid` なアトリビュートを設定するのがよいと思います。
その上で、blank なものとか、invalid なものを trait で上乗せしていくとわかりやすくなります。
例えば、こんな感じですね。
```rb
FactoryGirl.define do
  factory :applist do
    google_play_url "https://play.google.com/store/apps/details?id=com.kakao.talk"
    itunes_url "https://itunes.apple.com/in/app/kakaotalk/id362057947"

    trait :without_google_play_url do
      google_play_url nil
    end

    trait :with_invalid_google_play_url do
      google_play_url "https://play.google.com/store/apps/details?id=exampleexampleexampleexample"
    end

    trait :without_itunes_url do
      itunes_url nil
    end

    trait :with_invalid_itunes_url do
      itunes_url "https://itunes.apple.com/in/app/exampleexampleexample/id0123456789"
    end
  end
end
```

2016-10-02 13:55 UTC, kayhide requested changes
追加です。

あと、テスト中にネット経由でどこかのurlにアクセスしているますね。
テストが外部のシステムに依存してしまうのは基本的に避けましょう。
これについては別イシューであげておきます。

2016-10-02 13:55 UTC, kayhide commented on app/models/applist.rb
> +    rescue => e
インデントがズレてますね。

2016-10-02 13:55 UTC, kayhide commented on app/models/applist.rb
> +      puts e
`puts` は標準出力にでてしまうので問題ありですね。
`logger` を検討してみてください。
http://railsguides.jp/debugging_rails_applications.html#%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8%E9%80%81%E4%BF%A1

2016-10-02 13:55 UTC, kayhide commented on app/models/applist.rb
> +      return
`return` より、返り値を書く方がわかりやすいです。
`nil` と書いておくのがよいでしょう。

2016-10-04 00:34 UTC, kitaindia commented
レビューの指摘箇所を修正しました

テストで外部に通信が走るのは僕もちょっと気になってました。

2016-10-04 01:27 UTC, kayhide approved these changes
OK です。マージしてくださいませ。

2016-10-06 03:03 UTC, merged